micronaut:
    application:
        name: send-money
datasources:
    default:
        url: jdbc:h2:mem:db1;DB_CLOSE_DELAY=0;DB_CLOSE_ON_EXIT=TRUE
        username: sa
        password: ""
        driverClassName: org.h2.Driver
jpa:
    default:
        packages-to-scan:
            - 'send.money'
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                show_sql: false
